language: java
jdk:
- oraclejdk8

notifications:
  slack:
    secure: ebb71h5I/nX+0Ogdy/WDBHIaBfm8TTkH2d41AKyXKEHGrt1W25jM+5ZpWS3BSbadA2IrbV1gSMYrVYEhdumhpPa3Vy5rhTgRZl3BunSoR+PehNSaI2Orw6nAYbAWrxnXmQPAeW3JwZglTMM2ifZfcD8XGD5NdSEs9Eu64rQVJ/NB0JCyeYXAc60PEWUGzXpVYxgSC0GY7bkWeWAgaiSQKVo43jPiidAzKY1oV+OfZkY3rJMUI58/BAl7jh1m3NRYda7GhOuXhL60VlQv0zPoydJNME4l8MyVGQ6MixNOWkHhb4A5qPFG1m1dBYEVtx5OYxqRd4I7yoxy3eWzssQKQDbOSFcckzAX/F7H8HKajuHwIKMrNe2h664e0kMZ2LQRQi+kjYM7u7pKrUujtvIwEY8Y0HvTfPZHeXEDnfAfqjJoPmmrm5H3TNSZSqP6Jv/Zwx6kFrOwC4ar1X25hgLw3sxqKuwU8icWFkSeEXdlxAJwiTOTTC+7qCeetUxToPeyc9vZzuwKzVOVRQa7GU6QtotPE0WAfkzEsfFN70NSFBwZdro5B7FuFwsyW9RvBQJUHQb9UNqSYCMNanOqFqCUe7UFFTYxmX1XksKh8K2fIUxZ+HhgwvgA+gFx3nincMb70rgAMgr8SAR4nO0spGW33fCYaGNa7eYc4kUsG7nP37Y=
