language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: xQyuQ2IvUt3lwmozRlFUjWp6fTqgqkIFYZIxz4b9wtgC7JU9f2IHxgW8sRrHxi1TXY6xKFMpd/YKiCuwt+CyRK7BPj6wImFfxP1gCGghIh1z/3Sf4aqk4qRmDfxQIRpMC50Yr5fPUVRLup2AauvZam+BQY1nnACJY7icIr1EGh7kMxm79U8FjoG452fBPTZHaw58u+Yr0DOuNv9t22i2NnPGZZUgbKeWwT6jp2NnrONVzV6FfZqLhHWSe3Os+7U+b1ZMyUCCTNMnacXHJSxnbBLaxF3Le6j4NmJNDkpKARGzgHWDm6gnpVnLT8+vrHQjOY07MXNIF1snxD9vSE7ZSUtS1SXPeLLMfO9SDGohp3nmYUkI1za3RARl0X/+fNYnUb3sG4FwpM2s2u3Y0QNchK0pIvpIUmisWnm26FNqdl9RVdZcxUDBj7DHjtya6SIKpbiS+pyKfzueh5/8oOKDmW0WP+LaRmXK+m5So9a39mhjJtIsv4t0+oOOYvPArlbjyZPJie0qtGm/s6qmC5OW7et0ChZt8UibLwpAry9Xsjc9CYCD4rfLpU8AgdtZSunPypGLVAuT96HUcLc9UWAFiWWxq8bfyEoaQtFAeKbT9WCkq9H2K3hLSat2EgNSrFbAaqPK9djtuQ48+iyv2UOH/MeTzFS7ow/9yPY7UOfX2W8=
